name = "mynomad-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV namespace for rate limiting
# Replace YOUR_KV_NAMESPACE_ID with the actual ID from: wrangler kv:namespace create "RATE_LIMIT"
kv_namespaces = [
  { binding = "RATE_LIMIT", id = "7482e1a09548482f856f4e90f87a3475" }
]

# No vars needed - API key stored as secret via: wrangler secret put GEMINI_API_KEY
