name = "mynomad-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV namespace for rate limiting
# Replace YOUR_KV_NAMESPACE_ID with the actual ID from: wrangler kv:namespace create "RATE_LIMIT"
kv_namespaces = [
  { binding = "RATE_LIMIT", id = "YOUR_KV_NAMESPACE_ID" }
]

# No vars needed - API key stored as secret via: wrangler secret put OPENAI_API_KEY
